### ISSUE TITLE
 sgp30 support

### ISSUE THREAD

**Issue by DavidAntonin** [paulvha/svm30#1]
Hello,
can you add support for sgp30 with external tem/hum sensor?
Thank you

**Comment by paulvha** [comment]
Hi David,

The nice aspect about an SVM30 is that it combines the SGP30 and an external sensor SHTC1 on a single board. Hence I have not considered an other Hum / temp sensor. What sensor would you consider ?
regards,
Paul

**Comment by DavidAntonin** [comment]
Hi Paul,
SVM30 is very pricey on Aliexpress so I bought SGP30 + SHT31. 
Regards
David

**Comment by paulvha** [comment]
HI David

I understand. I am currently in the middle of working on another project but I had a look on github and see that Adafruit has created a library's for both

https://github.com/adafruit/Adafruit_SHT31
https://github.com/adafruit/Adafruit_SGP30

Not sure which boards you have but I expect you could use these for your project.

Maybe in the future another nice project for me, although I first consider the new SVM40 😉

regards,
Paul

________________________________
Van: DavidAntonin <notifications@github.com>
Verzonden: maandag 9 november 2020 09:30
Aan: paulvha/svm30 <svm30@noreply.github.com>
CC: paulvha <paulvha@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [paulvha/svm30] sgp30 support (#1)


Hi Paul,
SVM30 is very pricey on Aliexpress so I bought SGP30 + SHT31.
Regards
David

**Comment by paulvha** [comment]
closing old issues
